# Generated by Django 2.0.7 on 2020-08-04 09:35

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0003_auto_20200721_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocjena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst', models.TextField(blank=True)),
                ('ocjena', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst', models.TextField(blank=True)),
                ('broj_mjesta', models.IntegerField()),
                ('accepted', models.BooleanField(default=False)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_rute', models.CharField(max_length=30)),
                ('startingLocation', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), size=2), size=2)),
                ('endLocation', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), size=2), size=2)),
                ('cigarete_u_autu', models.BooleanField()),
                ('dozvoljen_prtljak', models.BooleanField()),
                ('datum_kreiranja', models.DateField(auto_now_add=True)),
                ('datum_i_vrijeme_polaska', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('broj_slobodnih_mjesta', models.IntegerField()),
                ('profil_vozaca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruta.Ruta'),
        ),
        migrations.AddField(
            model_name='ocjena',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ruta.Request'),
        ),
    ]
