# Generated by Django 2.0.7 on 2020-07-21 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0003_auto_20200721_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_rute', models.CharField(max_length=30)),
                ('cigarete_u_autu', models.BooleanField()),
                ('dozvoljen_prtljak', models.BooleanField()),
                ('datum_kreiranja', models.DateField(auto_now_add=True)),
                ('datum_i_vrijeme_polaska', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('broj_slobodnih_mjesta', models.IntegerField()),
                ('profil_vozaca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.Profile')),
            ],
        ),
    ]
