# Generated by Django 2.0.7 on 2020-07-21 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20200721_0954'),
        ('ruta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst', models.TextField(blank=True)),
                ('broj_mjesta', models.IntegerField()),
                ('accepted', models.BooleanField(default=False)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.Profile')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruta.Ruta')),
            ],
        ),
    ]
