# Generated by Django 2.0.7 on 2020-08-08 23:42

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20200808_2342'),
        ('ruta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'rating',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=30)),
                ('startingLocation', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), size=2), size=2)),
                ('endLocation', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), size=2), size=2)),
                ('cigarette_allowed', models.BooleanField()),
                ('luggage_allowed', models.BooleanField()),
                ('create_at', models.DateField(auto_now_add=True)),
                ('departure', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('empty_spots', models.IntegerField()),
                ('driver_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.Profile')),
            ],
            options={
                'db_table': 'route',
            },
        ),
        migrations.RemoveField(
            model_name='ocjena',
            name='request',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='profil_vozaca',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='tekst',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='profil',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='broj_mjesta',
            new_name='seats_number',
        ),
        migrations.RemoveField(
            model_name='request',
            name='ruta',
        ),
        migrations.AlterModelTable(
            name='request',
            table='request',
        ),
        migrations.DeleteModel(
            name='Ocjena',
        ),
        migrations.DeleteModel(
            name='Ruta',
        ),
        migrations.AddField(
            model_name='rating',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ruta.Request'),
        ),
        migrations.AddField(
            model_name='request',
            name='route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ruta.Route'),
            preserve_default=False,
        ),
    ]
