# Generated by Django 2.0.7 on 2020-07-21 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0002_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocjena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst', models.TextField(blank=True)),
                ('ocjena', models.DecimalField(decimal_places=2, max_digits=5)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ruta.Request')),
            ],
        ),
    ]
