# Generated by Django 2.0.7 on 2020-08-11 08:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0002_auto_20200808_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='endLocation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), size=2),
        ),
        migrations.AlterField(
            model_name='route',
            name='startingLocation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), size=2),
        ),
    ]
