# Generated by Django 2.0.7 on 2020-08-08 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20200721_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='adresa',
            new_name='adddress',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='goditste',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='datum_reg',
            new_name='reg_date',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='broj_tell',
            new_name='tel_number',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='Profile',
        ),
    ]
